// lib/core/constants/app_quotes.dart
const List<String> dailyQuotes = [
  "“A healthy outside starts from the inside.” – Robert Urich",
  "“If you keep good food in your fridge, you will eat good food.” – Errick McAdams",
  "“Physical fitness is not only one of the most important keys to a healthy body, it is the basic of dynamic and creative intellectual activity.” – John F. Kennedy",
  "“There is no health without mental health; mental health is too important to be left to the professionals alone, and mental health is everyone’s business.” – Vikram Patel",
  "“Those who have no time for healthy eating will sooner or later have to find the time for illness.” – Edward Stanley",
  "“What most people don’t realize is that food is not just calories: It’s information. It actually contains messages that communicate to every cell in the body.” – Dr. Mark Hyman",
  "“Sorry, there’s no magic bullet. You gotta eat healthy and live healthy to be healthy and look healthy. End of story.” – Morgan Spurlock",
  "“Good health is not something we can buy. However, it can be an extremely valuable savings account.” – Anne Wilson Schaef",
  "“Our bodies are our gardens – our wills are our gardeners.” – William Shakespeare",
  "“Self-care is not selfish. You cannot serve from an empty vessel.” – Eleanor Brown",
  "“The key to a healthy life is having a healthy mind.” – Richard Davidson",
  "“The doctor of the future will give no medicine, but will instruct his patients in care of the human frame, in diet, and in the cause and prevention of disease.” – Thomas Edison",
  "“I have chosen to be happy because it is good for my health.” – Voltaire",
  "“Some things you have to do every day. Eating seven apples on Saturday night instead of one a day just isn’t going to get the job done.” – Jim Rohn",
  "“A sad soul can be just as lethal as a germ.” – John Steinbeck",
  "“Keeping your body healthy is an expression of gratitude to the whole cosmos — the trees, the clouds, everything.” – Thich Nhat Hanh",
  "“So many people spend their health gaining wealth, and then have to spend their wealth to regain their health.” – A. J. Reb Materi",
  "“If you know the art of deep breathing, you have the strength, wisdom and courage of ten tigers.” – Chinese adage",
  "“It’s not until you get tired that you see how strong you really are.” – Shaun T",
  "“People who laugh actually live longer than those who don’t laugh. Few persons realize that health actually varies according to the amount of laughter.” – James J. Walsh",
  "“To keep the body in good health is a duty…otherwise we shall not be able to keep the mind strong and clear.” – Buddha",
  "“You can’t control what goes on outside, but you can control what goes on inside.” – Unknown",
  "“The ability to be in the present moment is a major component of mental wellness.” – Abraham Maslow",
  "“While weight loss is important, what's more important is the quality of food you put in your body - food is information that quickly changes your metabolism and genes.” – Dr. Mark Hyman",
  "“Take care of your body, it’s the only place you have to live.” – Jim Rohn",
  "“Wellness is the complete integration of body, mind, and spirit – the realization that everything we do, think, feel, and believe has an effect on our state of well-being.” – Greg Anderson",
  "“You can’t stop the waves, but you can learn to surf.” – Jon Kabat-Zinn",
  "“No matter how old you are, no matter how much you weigh, you can still control the health of your body.” – Dr. Harvey Cushing",
  "“You can't exercise your way out of a bad diet.” – Dr. Mark Hyman",
  "“Wellness is a connection of paths: knowledge and action.” – Joshua Holtz",
  "“It is health that is real wealth and not pieces of gold and silver.” – Mahatma Gandhi",
  "“A calm mind brings inner strength and self-confidence, so that’s very important for good health.” – Dalai Lama",
  "“It is not the bruises on the body that hurt. It is the wounds of the heart and the scars on the mind.” – Aisha Mirza",
  "“He who has health has hope and he who has hope has everything.” – Arabian Proverb",
  "“To get rich, never risk your health. For it is the truth that health is the wealth of wealth.” – Richard Baker",
  "“Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.” – Oprah Winfrey",
  "“The groundwork for all happiness is good health.” – Leigh Hunt",
  "“Your illness is not your identity. Your chemistry is not your character.” – Pastor Rick Warren",
  "“Early to bed and early to rise makes a man healthy, wealthy, and wise.” – Benjamin Franklin",
  "“The reason I exercise is for the quality of life I enjoy.” – Kenneth H. Cooper",
  "“If you want to feel good, you have to go out and do some good.” – Oprah Winfrey",
  "“Let thy food be thy medicine and thy medicine be thy food.” – Hippocrates",
  "“If you want a relaxed body, you can do it by relaxing your mind. If you want a relaxed mind, relax your body.” – Jay Winner",
  "“It is exercise alone that supports the spirits, and keeps the mind in vigor.” – Marcus Tullius Cicero",
  "“Keep your vitality. A life without health is like a river without water.” – Maxime Lagacé",
  "“Remain calm, because peace equals power.” – Joyce Meyer",
  "“What mental health needs are more sunlight, more candor, and more unashamed conversation.” – Glenn Close",
  "“A man’s health can be judged by which he takes two at a time — pills or stairs.” – Joan Welsh",
  "“Half the costs of illness are wasted on conditions that could be prevented.” – Dr. Joseph Pizzorno",
  "“Make eating fruits and vegetables a priority. This is so simple and beneficial, yet most people don’t do it.” – Nia Shanks",
  "“Some struggle is healthy. If you can embrace it rather than be angry, you can use it as your pilot light.” – Damon Wayans",
  "“The higher your energy level, the more efficient your body. The more efficient your body, the better you feel and the more you will use your talent to produce outstanding results.” – Anthony Robbins",
  "“The longer I live the more I see that I am never wrong about anything and that all the pains that I have so humbly taken to verify my notions have only wasted my time.” – George Bernard Shaw",
  "“The existence of illness in the body may no doubt be called a shadow of the true illness that is held by a man in his mind.” – Hazrat Khan",
  "“When health is absent, wisdom cannot reveal itself, art cannot manifest, strength cannot fight, wealth becomes useless, and intelligence cannot be applied.” – Herophilus",
  "“Happiness is the highest form of health.” – Dalai Lama",
  "“If you don’t do what’s best for your body, you’re the one who comes up on the short end.” – Julius Erving"
];